"""users table

Revision ID: f1cb1eb27731
Revises: 
Create Date: 2018-12-18 20:06:02.186806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cb1eb27731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=64), nullable=True),
    sa.Column('userPwd', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_userName'), 'user', ['userName'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_userName'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
